# Generated by Django 3.2.5 on 2021-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ideas/')),
                ('content', models.TextField()),
                ('interest', models.PositiveIntegerField()),
                ('devtool', models.CharField(choices=[('django', 'django'), ('spring', 'spring'), ('ruby', 'ruby'), ('None', 'None of these')], max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
