# Generated by Django 3.2.5 on 2021-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.CharField(choices=[('None', 'None of these'), ('ruby', 'ruby'), ('spring', 'spring'), ('django', 'django')], max_length=80, null=True),
        ),
    ]
