# Generated by Django 3.2.5 on 2021-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_post_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.CharField(choices=[('django', 'django'), ('None', 'None of these'), ('spring', 'spring'), ('ruby', 'ruby')], max_length=80, null=True),
        ),
    ]
